# Generated by Django 5.0.9 on 2026-06-28 13:35

import apps.core.mixins
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('facturation_comptabilite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('num_reception', models.CharField(max_length=50, unique=True, verbose_name='N° réception')),
                ('date_reception', models.DateField(default=datetime.date.today, verbose_name='Date de réception')),
                ('nature_echantillon', models.CharField(help_text='Ex: Béton, Sol, Eau, etc.', max_length=100, verbose_name="Nature de l'échantillon")),
                ('etat_essai', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20, verbose_name="État de l'essai")),
                ('etat_rapport', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=20, verbose_name='État du rapport')),
                ('charge_prelevement', models.CharField(blank=True, max_length=150, verbose_name='Chargé de prélèvement')),
                ('bordereau', models.CharField(blank=True, max_length=50, verbose_name="N° Bordereau d'envoi")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='commercial.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='commercial.dossier', verbose_name='Dossier')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='facturation_comptabilite.facture', verbose_name='Facture')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'ordering': ['-date_reception', '-id'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
    ]
