# Generated by Django 5.0.9 on 2026-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_receptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='nature_echantillon',
            field=models.CharField(max_length=100, verbose_name="Nature de l'échantillon"),
        ),
    ]
