# Generated by Django 5.0.9 on 2026-07-09 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_receptions', '0002_alter_reception_nature_echantillon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='reception',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='reception',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
    ]
