# Generated by Django 5.0.9 on 2026-06-28 13:35

import apps.core.mixins
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° Facture')),
                ('date_facture', models.DateField(default=datetime.date.today, verbose_name='Date Facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=4, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Montant TTC')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('PAYEE_PARTIEL', 'Payée Partiellement'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('envoye', models.BooleanField(default=False, verbose_name='Envoyée')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('accuse', models.BooleanField(default=False, verbose_name='Accusée de réception')),
                ('date_accuse', models.DateField(blank=True, null=True, verbose_name="Date de l'accusé")),
                ('validee_par_signature', models.BooleanField(default=False, verbose_name='Validée par signature')),
                ('difficulte_recouvrement', models.CharField(choices=[('RECOUVRABLE', 'Recouvrable'), ('DIFFICILE', 'Difficile'), ('NON_RECOUVRABLE', 'Non Recouvrable')], default='RECOUVRABLE', max_length=20, verbose_name='Difficulté de recouvrement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='commercial.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('decompte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='commercial.decompte', verbose_name='Décompte')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='commercial.devis', verbose_name='Devis')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='commercial.dossier', verbose_name='Dossier')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Envoyée par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'Facture Client',
                'verbose_name_plural': 'Factures Clients',
                'ordering': ['-date_facture', '-id'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Réf Encaissement')),
                ('date_encaissement', models.DateField(default=datetime.date.today, verbose_name="Date d'encaissement")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant Encaissé')),
                ('moyen_paiement', models.CharField(choices=[('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('EFFET', 'Effet'), ('ESPECES', 'Espèces'), ('VERSEMENT', 'Versement Direct')], max_length=20, verbose_name='Moyen de paiement')),
                ('reference_transaction', models.CharField(help_text='N° de chèque, référence virement, etc.', max_length=100, verbose_name='Réf Transaction / N° Chèque')),
                ('banque', models.CharField(blank=True, max_length=150, verbose_name='Banque émettrice')),
                ('compte_depot', models.CharField(blank=True, max_length=100, verbose_name='Compte de dépôt')),
                ('encaisse', models.BooleanField(default=True, verbose_name='Déposé/Encaissé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='finance.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Encaissement',
                'verbose_name_plural': 'Encaissements',
                'ordering': ['-date_encaissement', '-id'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Raison sociale')),
                ('ice', models.CharField(blank=True, max_length=15, null=True, verbose_name='ICE')),
                ('rc', models.CharField(blank=True, max_length=50, null=True, verbose_name='R.C.')),
                ('if_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identifiant Fiscal')),
                ('patente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patente')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference_interne', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Réf Interne')),
                ('reference_fournisseur', models.CharField(max_length=100, verbose_name='N° Facture Fournisseur')),
                ('date_facture', models.DateField(verbose_name='Date Facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TTC')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE_PARTIEL', 'Payée Partiellement'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='finance.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Facture Fournisseur',
                'verbose_name_plural': 'Factures Fournisseurs',
                'ordering': ['-date_facture', '-id'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Réf Paiement')),
                ('date_paiement', models.DateField(default=datetime.date.today, verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant Payé')),
                ('moyen_paiement', models.CharField(choices=[('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('EFFET', 'Effet'), ('ESPECES', 'Espèces'), ('VERSEMENT', 'Versement Direct')], max_length=20, verbose_name='Moyen de paiement')),
                ('reference_transaction', models.CharField(max_length=100, verbose_name='Réf Transaction / N° Chèque')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('facture_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.facturefournisseur', verbose_name='Facture Fournisseur')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'Paiement Fournisseur',
                'verbose_name_plural': 'Paiements Fournisseurs',
                'ordering': ['-date_paiement', '-id'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Réf Caisse')),
                ('date_mouvement', models.DateField(default=datetime.date.today, verbose_name='Date Mouvement')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de fonds'), ('SORTIE', 'Sortie de fonds')], max_length=10, verbose_name='Type de mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif / Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('encaissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse', to='finance.encaissement', verbose_name='Encaissement Client')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse', to='finance.paiement', verbose_name='Paiement Fournisseur')),
            ],
            options={
                'verbose_name': 'Mouvement de Caisse',
                'verbose_name_plural': 'Mouvements de Caisse',
                'ordering': ['-date_mouvement', '-id'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Recouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('statut_recouvrement', models.CharField(choices=[('A_RAPPELER', 'À rappeler'), ('RELANCE_1', 'Relance 1 envoyée'), ('RELANCE_2', 'Relance 2 envoyée'), ('CONTENTIEUX', 'Dossier Contentieux'), ('RESOLU', 'Résolu')], default='A_RAPPELER', max_length=30, verbose_name='Statut Recouvrement')),
                ('dernier_rappel', models.DateField(blank=True, null=True, verbose_name='Dernier rappel')),
                ('nombre_rappels', models.PositiveIntegerField(default=0, verbose_name='Nombre de rappels')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires de suivi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement', to='finance.facture', verbose_name='Facture')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'Dossier de Recouvrement',
                'verbose_name_plural': 'Dossiers de Recouvrement',
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
    ]
