# Generated by Django 5.0.9 on 2026-07-09 17:34

import apps.core.mixins
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0010_remove_decompte_ao_adjuge_remove_caution_ao_adjuge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AOSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference_ao', models.CharField(help_text="Référence externe officielle de l'avis d'AO", max_length=100, unique=True, verbose_name="référence de l'appel d'offres")),
                ('objet', models.CharField(max_length=255, verbose_name='objet du marché')),
                ('date_limite', models.DateTimeField(help_text='Ouverture des plis', verbose_name='date et heure limite de dépôt')),
                ('estimation_initiale', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="estimation maître d'ouvrage")),
                ('montant_soumission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='montant de notre soumission')),
                ('statut', models.CharField(choices=[('PREPARATION', 'En préparation'), ('SOUMIS', 'Soumis / Déposé'), ('REJETE', 'Rejeté / Non retenu'), ('ADJUGE', 'Adjugé / Remporté')], default='PREPARATION', max_length=20, verbose_name='statut de soumission')),
                ('remarques', models.TextField(blank=True, verbose_name='remarques / composition du groupement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appels_offres_soumis', to='commercial.client', verbose_name="maître d'ouvrage (Client)")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': "appel d'offres soumission",
                'verbose_name_plural': "appels d'offres soumissions",
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AOAdjuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date_adjudication', models.DateField(default=django.utils.timezone.now, verbose_name="date d'adjudication")),
                ('montant_final', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant final adjugé (TTC)')),
                ('caution_definitive_deposee', models.BooleanField(default=False, verbose_name='caution définitive déposée')),
                ('date_notification', models.DateField(blank=True, help_text='Ordre de Service de commencement des prestations', null=True, verbose_name="date de notification de l'OS")),
                ('statut', models.CharField(choices=[('EN_COURS', "En cours d'exécution"), ('TERMINE', 'Marché clôturé / Réception définitive'), ('RESILIE', 'Marché résilié')], default='EN_COURS', max_length=20, verbose_name="statut d'exécution")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('ao_soumission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjudication', to='marches.aosoumission', verbose_name="appel d'offres d'origine")),
            ],
            options={
                'verbose_name': "appel d'offres adjugé",
                'verbose_name_plural': "appels d'offres adjugés",
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('banque', models.CharField(max_length=150, verbose_name='banque émettrice')),
                ('type_caution', models.CharField(choices=[('PROVISOIRE', 'Caution Provisoire (Soumission)'), ('DEFINITIVE', 'Caution Définitive (Exécution)'), ('RETENUE_GARANTIE', 'Caution de Retenue de Garantie')], max_length=30, verbose_name='type de caution')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant caution (MAD)')),
                ('date_depot', models.DateField(default=django.utils.timezone.now, verbose_name='date de dépôt / émission')),
                ('date_mainlevee', models.DateField(blank=True, null=True, verbose_name='date de mainlevée')),
                ('statut', models.CharField(choices=[('DEPOSE', 'Déposée'), ('LIBERE', 'Libérée / Mainlevée obtenue'), ('CONFISQUE', 'Confisquée par le client')], default='DEPOSE', max_length=20, verbose_name='statut')),
                ('ao_adjuge', models.ForeignKey(blank=True, help_text='Requis si caution définitive ou retenue de garantie', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cautions', to='marches.aoadjuge', verbose_name='marché adjugé')),
                ('ao_soumission', models.ForeignKey(blank=True, help_text='Requis si caution provisoire', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cautions', to='marches.aosoumission', verbose_name="appel d'offres soumission")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'caution',
                'verbose_name_plural': 'cautions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Decompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='référence décompte')),
                ('numero_decompte', models.PositiveIntegerField(verbose_name='numéro de décompte')),
                ('date_decompte', models.DateField(default=django.utils.timezone.now, verbose_name="date d'établissement")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant H.T.')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant T.T.C.')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', "Validé par maître d'œuvre"), ('PAYE', 'Encaissé / Réglé')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('ao_adjuge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decomptes', to='marches.aoadjuge', verbose_name='marché lié')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decomptes', to='commercial.dossier', verbose_name='dossier de chantier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'décompte',
                'verbose_name_plural': 'décomptes',
                'ordering': ['-date_decompte', '-numero_decompte'],
                'abstract': False,
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResultatBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date_evaluation', models.DateField(default=django.utils.timezone.now, verbose_name="date d'évaluation")),
                ('note_satisfaction', models.PositiveIntegerField(help_text='1 = Très insatisfait, 5 = Très satisfait', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note de satisfaction (1 à 5)')),
                ('commentaires', models.TextField(blank=True, verbose_name="remarques & opportunités d'amélioration")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_bc', to='commercial.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_bc', to='commercial.dossier', verbose_name='dossier concerné')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'résultat BC / enquête',
                'verbose_name_plural': 'résultats BC / enquêtes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
    ]
