# Generated by Django 5.0.9 on 2026-07-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0002_aoadjuge_annule_le_aoadjuge_annule_par_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultatbc',
            options={'ordering': ['-created_at'], 'verbose_name': 'résultat BC', 'verbose_name_plural': 'résultats BC'},
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='client',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='commentaires',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='date_evaluation',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='note_satisfaction',
        ),
        migrations.AddField(
            model_name='resultatbc',
            name='ao_soumission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='marches.aosoumission', verbose_name="appel d'offres soumission"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatbc',
            name='entreprise_attributaire',
            field=models.CharField(blank=True, max_length=255, verbose_name='entreprise attributaire'),
        ),
        migrations.AddField(
            model_name='resultatbc',
            name='etat_reponse',
            field=models.CharField(choices=[('NON_ATTRIBUE', 'Non attribué'), ('ADJUGE', 'Adjugé'), ('REJETE', 'Rejeté')], default='NON_ATTRIBUE', max_length=20, verbose_name='état de la réponse'),
        ),
        migrations.AddField(
            model_name='resultatbc',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='montant'),
        ),
        migrations.AddField(
            model_name='resultatbc',
            name='nombre_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de participants'),
        ),
    ]
