# Generated by Django 5.0.9 on 2026-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0003_alter_resultatbc_options_remove_resultatbc_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoadjuge',
            name='acheve',
            field=models.BooleanField(default=False, verbose_name='achevé'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='delai_realisation',
            field=models.CharField(blank=True, max_length=100, verbose_name='délai de réalisation'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='montant_encaisse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='montant encaissé'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='reste_a_realiser',
            field=models.TextField(blank=True, verbose_name='reste à réaliser'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='solde',
            field=models.BooleanField(default=False, verbose_name='soldé'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='travaux_realises',
            field=models.TextField(blank=True, verbose_name='travaux réalisés'),
        ),
        migrations.AddField(
            model_name='caution',
            name='numero_caution',
            field=models.CharField(blank=True, max_length=100, verbose_name='numéro de caution'),
        ),
        migrations.AddField(
            model_name='caution',
            name='renvoyee_banque',
            field=models.BooleanField(default=False, verbose_name='renvoyée à la banque'),
        ),
        migrations.AlterField(
            model_name='aoadjuge',
            name='montant_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='montant final adjugé (TTC)'),
        ),
    ]
