# Generated by Django 5.0.9 on 2026-07-13 08:58

import django.db.models.deletion
from django.db import migrations, models

def clean_numeric_fields(apps, schema_editor):
    AOAdjuge = apps.get_model('marches', 'AOAdjuge')
    for obj in AOAdjuge.objects.all():
        r = str(obj.reste_a_realiser or '').strip()
        r = r.replace(',', '.')
        try:
            float(r)
            obj.reste_a_realiser = r
        except ValueError:
            obj.reste_a_realiser = '0.00'

        t = str(obj.travaux_realises or '').strip()
        t = t.replace(',', '.')
        try:
            float(t)
            obj.travaux_realises = t
        except ValueError:
            obj.travaux_realises = '0.00'

        obj.save(update_fields=['reste_a_realiser', 'travaux_realises'])


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_bonlivraison_date_accuse_and_more'),
        ('marches', '0004_aoadjuge_acheve_aoadjuge_delai_realisation_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_numeric_fields, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='aoadjuge',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='num_marche_bc',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° marché ou BC'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='objet',
            field=models.TextField(blank=True, verbose_name='objet'),
        ),
        migrations.AddField(
            model_name='aoadjuge',
            name='type_marche_bc',
            field=models.CharField(choices=[('MARCHE', 'Marché'), ('BC', 'Bon de commande')], default='MARCHE', max_length=20, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='aosoumission',
            name='adjudicataire',
            field=models.CharField(blank=True, max_length=255, verbose_name='adjudicataire'),
        ),
        migrations.AddField(
            model_name='aosoumission',
            name='ao_bc',
            field=models.CharField(choices=[('AO', "Appel d'Offres"), ('BC', 'Bon de Commande')], default='AO', max_length=2, verbose_name='AO / BC'),
        ),
        migrations.AddField(
            model_name='aosoumission',
            name='heure_limite',
            field=models.TimeField(blank=True, help_text='Heure limite de dépôt des plis', null=True, verbose_name='heure limite de dépôt'),
        ),
        migrations.AddField(
            model_name='aosoumission',
            name='lieu_execution',
            field=models.CharField(blank=True, max_length=255, verbose_name="lieu d'exécution"),
        ),
        migrations.AddField(
            model_name='aosoumission',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='montant'),
        ),
        migrations.AddField(
            model_name='aosoumission',
            name='reponse',
            field=models.CharField(blank=True, max_length=100, verbose_name='réponse'),
        ),
        migrations.AddField(
            model_name='aosoumission',
            name='statut_resultat',
            field=models.CharField(choices=[('ADJUGE', 'Adjugé'), ('NON_ADJUGE', 'Non adjugé'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20, verbose_name='résultat'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='chemin_decompte',
            field=models.FileField(blank=True, null=True, upload_to='decomptes/', verbose_name='chemin décompte'),
        ),
        migrations.AlterField(
            model_name='aoadjuge',
            name='ao_soumission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjudication', to='marches.aosoumission', verbose_name="appel d'offres d'origine"),
        ),
        migrations.AlterField(
            model_name='aoadjuge',
            name='reste_a_realiser',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='reste à réaliser'),
        ),
        migrations.AlterField(
            model_name='aoadjuge',
            name='travaux_realises',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='travaux réalisés'),
        ),
        migrations.AlterField(
            model_name='aosoumission',
            name='date_limite',
            field=models.DateField(help_text='Date limite de dépôt des plis', verbose_name='date limite de dépôt'),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decomptes', to='commercial.dossier', verbose_name='dossier de chantier'),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='montant_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='montant H.T.'),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='montant_tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='montant TVA'),
        ),
    ]
