# Generated by Django 5.0.9 on 2026-07-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0005_aoadjuge_client_aoadjuge_num_marche_bc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caution',
            name='client',
            field=models.TextField(blank=True, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='caution',
            name='num_ao',
            field=models.CharField(blank=True, max_length=100, verbose_name="n° appel d'offre"),
        ),
        migrations.AddField(
            model_name='caution',
            name='num_marche_bc',
            field=models.CharField(blank=True, max_length=100, verbose_name='n° marché ou BC'),
        ),
        migrations.AddField(
            model_name='caution',
            name='objet',
            field=models.TextField(blank=True, verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='caution',
            name='ao_adjuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautions', to='marches.aoadjuge', verbose_name='marché adjugé'),
        ),
        migrations.AlterField(
            model_name='caution',
            name='ao_soumission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautions', to='marches.aosoumission', verbose_name="appel d'offres soumission"),
        ),
        migrations.AlterField(
            model_name='caution',
            name='banque',
            field=models.CharField(blank=True, max_length=150, verbose_name='banque émettrice'),
        ),
        migrations.AlterField(
            model_name='caution',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='montant caution (MAD)'),
        ),
        migrations.AlterField(
            model_name='caution',
            name='type_caution',
            field=models.CharField(choices=[('PROVISOIRE', 'Caution Provisoire'), ('DEFINITIVE', 'Caution Définitive')], max_length=30, verbose_name='type de caution'),
        ),
    ]
