# Generated by Django 5.0.9 on 2026-06-26 16:57

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='nouvelle valeur'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='ancienne valeur'),
        ),
    ]
