# Generated by Django 5.0.9 on 2026-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_new_value_alter_auditlog_old_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('CANCEL', 'Annulation'), ('RESTORE', 'Restauration'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('VALIDATE', 'Validation'), ('PRINT', 'Impression'), ('UPLOAD', 'Upload fichier'), ('DOWNLOAD', 'Téléchargement')], max_length=20, verbose_name="type d'action"),
        ),
    ]
