# Generated by Django 5.0.9 on 2026-07-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation_comptabilite', '0001_initial'),
        ('marches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='decompte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='marches.decompte', verbose_name='Décompte'),
        ),
    ]
