# Generated by Django 5.0.9 on 2026-07-09 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation_comptabilite', '0002_alter_facture_decompte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encaissement',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
        migrations.AddField(
            model_name='facture',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='facture',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé'),
        ),
    ]
