# Generated by Django 5.0.9 on 2026-07-15 12:38

import apps.core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation_comptabilite', '0003_encaissement_annule_le_encaissement_annule_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('est_annule', models.BooleanField(db_index=True, default=False, help_text='Si True, cet enregistrement est annulé (non supprimé physiquement).', verbose_name='est annulé')),
                ('annule_le', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('num_prix', models.CharField(blank=True, max_length=50, verbose_name='N° prix')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('quantite', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Prix unitaire (H.T)')),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='annulé par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation_comptabilite.facture', verbose_name='Facture')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'Ligne de Facture',
                'verbose_name_plural': 'Lignes de Facture',
                'ordering': ['id'],
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
    ]
