# Generated by Django 5.0.9 on 2026-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation_comptabilite', '0004_lignefacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='avec_ras',
            field=models.CharField(choices=[('Non', 'Non'), ('OUI_10', '10%'), ('OUI_15', '15%')], default='Non', max_length=10, verbose_name='Avec RAS'),
        ),
        migrations.AddField(
            model_name='facture',
            name='bc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bon de commande (BC)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='delai',
            field=models.PositiveIntegerField(default=30, verbose_name='Délai de règlement (jours)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='projet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='facture',
            name='synthese_modification',
            field=models.TextField(blank=True, null=True, verbose_name='Synthèse de modification'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('SITUATION', 'Situation'), ('DIRECTE', 'Directe'), ('AVOIR', 'Avoir')], default='DIRECTE', max_length=50, verbose_name='Type facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
    ]
