# Generated by Django 5.0.9 on 2026-07-15 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation_comptabilite', '0005_facture_avec_ras_facture_bc_facture_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant TVA'),
        ),
    ]
