# Generated by Django 5.0.9 on 2026-06-28 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='accuse',
            field=models.BooleanField(default=False, verbose_name='accusé de réception'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='date_envoi',
            field=models.DateField(blank=True, null=True, verbose_name="date d'envoi"),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='envoi_par',
            field=models.CharField(blank=True, max_length=150, verbose_name='envoi par'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='envoye',
            field=models.BooleanField(default=False, verbose_name='envoyé'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='saisie_le',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='saisie le'),
        ),
    ]
