# Generated by Django 5.0.9 on 2026-06-30 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_bonlivraison_accuse_bonlivraison_date_envoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mle',
            field=models.CharField(blank=True, max_length=50, verbose_name='mle'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville'),
        ),
        migrations.AddField(
            model_name='devis',
            name='reception_bc',
            field=models.BooleanField(default=False, verbose_name='réception BC'),
        ),
        migrations.AddField(
            model_name='devis',
            name='ref_bc',
            field=models.CharField(blank=True, max_length=100, verbose_name='référence BC'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='commande',
            field=models.CharField(blank=True, max_length=100, verbose_name='commande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='etat_accreditation',
            field=models.CharField(choices=[('ACCREDITE', 'Accrédité'), ('NON_ACCREDITE', 'Non accrédité')], default='NON_ACCREDITE', max_length=20, verbose_name="état d'accréditation"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='prestation',
            field=models.CharField(blank=True, max_length=100, verbose_name='prestation'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='accord_client',
            field=models.CharField(choices=[('ACCORD', 'Accordé'), ('REFUS', 'Refusé'), ('ATTENTE', 'En attente')], default='ATTENTE', max_length=20, verbose_name='accord client'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='decision_labo',
            field=models.CharField(choices=[('ACCORD', 'Accordé'), ('REFUS', 'Refusé'), ('ATTENTE', 'En attente')], default='ATTENTE', max_length=20, verbose_name='décision labo'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revues', to='commercial.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='ref_piece_jointe',
            field=models.CharField(blank=True, max_length=100, verbose_name='référence pièce jointe'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='référence revue'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='type_revue',
            field=models.CharField(blank=True, max_length=100, verbose_name='type de revue'),
        ),
    ]
