# Generated by Django 5.0.9 on 2026-06-30 14:56

import apps.core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_client_mle_client_telephone_2_client_ville_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(blank=True, max_length=50, verbose_name='CIN'),
        ),
        migrations.AddField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='client',
            name='gsm',
            field=models.CharField(blank=True, max_length=30, verbose_name='GSM'),
        ),
        migrations.AddField(
            model_name='client',
            name='representant',
            field=models.CharField(blank=True, max_length=150, verbose_name='représentant'),
        ),
        migrations.AddField(
            model_name='client',
            name='synthese_modification',
            field=models.TextField(blank=True, verbose_name='synthèse de modification'),
        ),
        migrations.AddField(
            model_name='devis',
            name='synthese_modification',
            field=models.TextField(blank=True, verbose_name='synthèse de modification'),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_devis',
            field=models.CharField(blank=True, max_length=100, verbose_name='type devis'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='commentaire'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_os',
            field=models.DateField(blank=True, null=True, verbose_name="date de l'ordre de service"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='delai_paiement',
            field=models.IntegerField(default=0, verbose_name='délai de paiement (jours)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='echeance_facturation',
            field=models.CharField(blank=True, default='A la réception', max_length=100, verbose_name='échéance de facturation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, verbose_name='entreprise'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='mode_reglement',
            field=models.CharField(blank=True, default='HT', max_length=50, verbose_name='mode de règlement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='synthese_modification',
            field=models.TextField(blank=True, verbose_name='synthèse de modification'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='type_affaire',
            field=models.CharField(blank=True, max_length=100, verbose_name='type affaire'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='discussion_client',
            field=models.TextField(blank=True, verbose_name='discussion pertinente avec client'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='etat_revue',
            field=models.CharField(blank=True, default='Initiale', max_length=100, verbose_name='état de revue'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='lieu_execution',
            field=models.CharField(blank=True, max_length=255, verbose_name="lieu d'exécution"),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='nature_prestation',
            field=models.CharField(blank=True, default='Essais', max_length=100, verbose_name='nature de la prestation'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='objet_modification',
            field=models.TextField(blank=True, verbose_name='objet de modification'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q10_avis',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NA', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q10_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q11_declaration',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NA', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q11_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q12_equipements',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q12_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q13_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q13_ressources',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q14_methodes_choisies',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q14_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q1_exigences',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q1_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q2_methode',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q2_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q3_incertitudes',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NON', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q3_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q4_echantillonnage',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NA', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q4_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q5_acheminement',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q5_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q6_conservation',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q6_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q7_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q7_soustraitance',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NON', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q8_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q8_transmission',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q9_cooperation',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='q9_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='ref_ao_bc',
            field=models.CharField(blank=True, max_length=100, verbose_name='référence AO/BC'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='sortie_decision',
            field=models.CharField(blank=True, default='OUI', max_length=50, verbose_name='décision'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='sortie_pieces_ref',
            field=models.CharField(blank=True, max_length=255, verbose_name='pièces de référence'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='sortie_resultat',
            field=models.CharField(blank=True, default='Proposition transmise au client', max_length=255, verbose_name='résultat'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='type_reception_demande',
            field=models.CharField(blank=True, default='Au laboratoire', max_length=100, verbose_name='type réception de la demande'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='validation_date',
            field=models.DateField(blank=True, null=True, verbose_name='réalisée le'),
        ),
        migrations.AddField(
            model_name='revuedemande',
            name='validation_technique',
            field=models.CharField(blank=True, max_length=150, verbose_name='pour le service technique'),
        ),
        migrations.CreateModel(
            name='DetailDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('num_prix', models.CharField(blank=True, max_length=50, verbose_name='N° prix')),
                ('designation', models.CharField(max_length=255, verbose_name='désignation')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='unité')),
                ('quantite', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='prix unitaire (H.T)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commercial.devis', verbose_name='devis')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'détail du devis',
                'verbose_name_plural': 'détails du devis',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.core.mixins.AuditableMixin, models.Model),
        ),
    ]
