# Generated by Django 5.0.9 on 2026-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_client_cin_client_fax_client_gsm_client_representant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revuedemande',
            name='q10_avis',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NA', max_length=5, verbose_name='10. Le client demande avis et interprétation'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q10_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q11_declaration',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NA', max_length=5, verbose_name='11. Le client demande une déclaration de conformité'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q11_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q12_equipements',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='12. Disponibilité et conformité des équipements'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q12_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q13_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q13_ressources',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='13. Disponibilité des ressources humaines compétentes'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q14_methodes_choisies',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='14. Les méthodes choisies (norme, etc.) sont appropriées et capables de répondre aux exigences du client'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q14_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q1_exigences',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='1. Les exigences du client (données du marché) sont : Définies, Documentées et Comprises'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q1_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q2_methode',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='2. La méthode demandée par le client est appropriée et/ou non périmée'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q2_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q3_incertitudes',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NON', max_length=5, verbose_name='3. Demande des incertitudes sur les résultats'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q3_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q4_echantillonnage',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NA', max_length=5, verbose_name='4. Prestation échantillonnage'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q4_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q5_acheminement',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='5. Acheminement des échantillons au laboratoire sous la responsabilité du client'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q5_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q6_conservation',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name="6. Période de conservation des échantillons au laboratoire après émission des rapports d'essais"),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q6_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q7_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q7_soustraitance',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='NON', max_length=5, verbose_name='7. Possibilité de sous-traitance de la prestation'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q8_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q8_transmission',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='8. Les modalités de transmission du rapport'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q9_cooperation',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NA', 'N/A')], default='OUI', max_length=5, verbose_name='9. Coopération, conseil et informations demandés'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='q9_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note / Constat'),
        ),
    ]
