# Generated by Django 5.0.9 on 2026-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_revuedemande_q10_avis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revuedemande',
            name='etat_revue',
            field=models.CharField(blank=True, choices=[('Initiale', 'Initiale'), ('Modifiee', 'Modifiée'), ('Validee', 'Validée')], default='Initiale', max_length=100, verbose_name='état de revue'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='nature_prestation',
            field=models.CharField(blank=True, choices=[('Essais', 'Essais'), ('Etudes', 'Études'), ('Controle', 'Contrôle'), ('Assistance', 'Assistance technique')], default='Essais', max_length=100, verbose_name='nature de la prestation'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='type_reception_demande',
            field=models.CharField(blank=True, choices=[('Au laboratoire', 'Au laboratoire'), ('Sur chantier', 'Sur chantier'), ('Par courrier', 'Par courrier / transporteur')], default='Au laboratoire', max_length=100, verbose_name='type réception de la demande'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='type_revue',
            field=models.CharField(blank=True, choices=[('DEMANDE', 'Demande'), ('CONTRAT', 'Contrat'), ('AVENANT', 'Avenant')], default='DEMANDE', max_length=100, verbose_name='type de revue'),
        ),
    ]
