# Generated by Django 5.0.9 on 2026-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_alter_revuedemande_etat_revue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revuedemande',
            name='sortie_decision',
            field=models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], default='OUI', max_length=50, verbose_name='décision'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='sortie_resultat',
            field=models.CharField(blank=True, choices=[('Proposition transmise au client', 'Proposition transmise au client'), ('Faisabilite confirmee', 'Faisabilité confirmée'), ('Demande rejetee', 'Demande rejetée')], default='Proposition transmise au client', max_length=255, verbose_name='résultat'),
        ),
    ]
