# Generated by Django 5.0.9 on 2026-06-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_alter_revuedemande_sortie_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='echeance_facturation',
            field=models.CharField(choices=[('RECEPTION', 'A la réception'), ('FIN_MOIS', 'Fin de mois'), ('30_JOURS', 'A 30 jours'), ('60_JOURS', 'A 60 jours')], default='RECEPTION', max_length=100, verbose_name='échéance de facturation'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='mode_reglement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement Bancaire'), ('TRAITE', 'Traite (LCN)')], default='VIREMENT', max_length=50, verbose_name='mode de règlement'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='type_affaire',
            field=models.CharField(choices=[('BATIMENT', 'Bâtiment'), ('GENIE_CIVIL', 'Génie Civil'), ('ROUTE', 'Route / Infrastructure'), ('HYDRAULIQUE', 'Hydraulique'), ('GEOTECHNIQUE', 'Géotechnique'), ('AUTRE', 'Autre')], default='BATIMENT', max_length=100, verbose_name='type affaire'),
        ),
    ]
