# Generated by Django 5.0.9 on 2026-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_alter_dossier_echeance_facturation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aosoumission',
            name='reference_ao',
            field=models.CharField(help_text="Référence externe officielle de l'avis d'AO", max_length=100, unique=True, verbose_name="référence de l'appel d'offres"),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='numero_decompte',
            field=models.PositiveIntegerField(verbose_name='numéro de décompte'),
        ),
        migrations.AlterField(
            model_name='detailbonlivraison',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='désignation / livrable'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='nom_projet',
            field=models.CharField(max_length=255, verbose_name='nom du projet / affaire'),
        ),
        migrations.AlterField(
            model_name='revuedemande',
            name='objet',
            field=models.CharField(max_length=255, verbose_name='objet du projet'),
        ),
    ]
