# Generated by Django 5.0.9 on 2026-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_alter_aosoumission_reference_ao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='ao_adjuge',
        ),
        migrations.RemoveField(
            model_name='caution',
            name='ao_adjuge',
        ),
        migrations.RemoveField(
            model_name='aosoumission',
            name='client',
        ),
        migrations.RemoveField(
            model_name='aosoumission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='aosoumission',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='caution',
            name='ao_soumission',
        ),
        migrations.RemoveField(
            model_name='caution',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='caution',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='client',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='resultatbc',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='devis',
            name='type_devis',
            field=models.CharField(blank=True, choices=[('BATIMENT', 'Bâtiment'), ('GENIE_CIVIL', 'Génie Civil'), ('ROUTE', 'Route / Infrastructure'), ('HYDRAULIQUE', 'Hydraulique'), ('GEOTECHNIQUE', 'Géotechnique'), ('AUTRE', 'Autre')], max_length=100, verbose_name='type devis'),
        ),
        migrations.DeleteModel(
            name='AOAdjuge',
        ),
        migrations.DeleteModel(
            name='AOSoumission',
        ),
        migrations.DeleteModel(
            name='Caution',
        ),
    ]
