# Generated by Django 5.0.9 on 2026-07-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_remove_decompte_ao_adjuge_remove_caution_ao_adjuge_and_more'),
        ('facturation_comptabilite', '0002_alter_facture_decompte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decompte',
        ),
        migrations.DeleteModel(
            name='ResultatBC',
        ),
    ]
