# Generated by Django 5.0.9 on 2026-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_bonlivraison_annule_le_bonlivraison_annule_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='validee_par_client',
            field=models.BooleanField(default=False, verbose_name='validée par client'),
        ),
    ]
