# Generated by Django 5.0.9 on 2026-07-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_convention_validee_par_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='date_accuse',
            field=models.DateField(blank=True, null=True, verbose_name="date d'accusé"),
        ),
        migrations.AddField(
            model_name='detailbonlivraison',
            name='ref_rapport',
            field=models.CharField(blank=True, max_length=100, verbose_name='référence rapport'),
        ),
    ]
