# Generated by Django 5.0.9 on 2026-07-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_bonlivraison_date_accuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='destinataire',
            field=models.CharField(blank=True, help_text='Nom de la personne physique qui reçoit les PV', max_length=255, verbose_name='réceptionné par (destinataire)'),
        ),
    ]
