# Generated by Django 5.0.9 on 2026-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0015_alter_bonlivraison_destinataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='objet',
            field=models.TextField(blank=True, verbose_name='objet de la livraison'),
        ),
    ]
