# Generated by Django 5.0.9 on 2026-07-09 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DroitAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('service_administratif', 'Service Administratif'), ('service_technique', 'Service Technique'), ('service_qualite', 'Service Qualité'), ('service_metrologie', 'Service Métrologie & Matériel'), ('espace_user', 'Espace Utilisateur'), ('ged_archive', 'GED Archive'), ('service_informatique', 'Service Informatique'), ('parametrage', 'Paramétrage')], max_length=50, verbose_name='service')),
                ('module', models.CharField(choices=[('commercial', 'Commercial'), ('marches', 'Marchés'), ('facturation_comptabilite', 'Facturation & Comptabilité'), ('achats_logistique', 'Achats & Logistique'), ('gestion_ressources_humaines', 'Ressources Humaines'), ('table_receptions', 'Table des Réceptions'), ('gestion_laboratoire', 'Gestion Laboratoire'), ('formation_qualification', 'Formation & Qualification'), ('gestion_documentaire', 'Gestion Documentaire'), ('fiche_progres', 'Fiche de Progrès'), ('inventaire_materiel', 'Inventaire Matériel'), ('fiche_vie', 'Fiche de Vie'), ('etalonnage_interne', 'Étalonnage Interne'), ('maj_incertitude', 'MAJ Incertitude'), ('maj_elements_etalonner', 'MAJ Éléments à Étalonner'), ('maj_mouvement_materiel', 'Mouvement Matériel'), ('plannings_metrologie', 'Plannings'), ('capabilite', 'Capabilité'), ('exploitation_metrologique', 'Exploitation Métrologique'), ('verification_etuves', 'Vérification Étuves'), ('parametres_metrologie', 'Paramètres Métrologie'), ('conges', 'Congés'), ('attestations', 'Attestations'), ('demandes_achat', "Demandes d'Achat"), ('specimen_signature', 'Spécimen Signature'), ('archive_ged', 'Archive GED'), ('services_familles_ged', 'Services/Familles GED'), ('droits_ged', 'Droits GED'), ('suivi_modifications', 'Suivi Modifications'), ('gestion_droits_acces', "Gestion Droits d'Accès"), ('donnees_informatique', 'Données Informatique'), ('parametrage_general', 'Paramétrage Général')], max_length=60, verbose_name='module')),
                ('peut_voir', models.BooleanField(default=False, verbose_name='peut voir')),
                ('peut_ajouter', models.BooleanField(default=False, verbose_name='peut ajouter')),
                ('peut_modifier', models.BooleanField(default=False, verbose_name='peut modifier')),
                ('peut_annuler', models.BooleanField(default=False, verbose_name='peut annuler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits_acces', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "droit d'accès",
                'verbose_name_plural': "droits d'accès",
                'ordering': ['user__username', 'service', 'module'],
                'unique_together': {('user', 'service', 'module')},
            },
        ),
    ]
