# Generated by Django 5.0.9 on 2026-07-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_droits_acces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droitacces',
            name='module',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('marches', 'Marchés'), ('facturation_comptabilite', 'Facturation & Comptabilité'), ('achats_logistique', 'Achats & Logistique'), ('gestion_ressources_humaines', 'Ressources Humaines'), ('table_receptions', 'Table des Réceptions'), ('gestion_laboratoire', 'Gestion Laboratoire'), ('formation_qualification', 'Formation & Qualification'), ('gestion_documentaire', 'Gestion Documentaire'), ('fiche_progres', 'Fiche de Progrès'), ('inventaire_materiel', 'Inventaire Matériel'), ('fiche_vie', 'Fiche de Vie'), ('etalonnage_interne', 'Étalonnage Interne'), ('maj_incertitude', 'MAJ Incertitude'), ('maj_elements_etalonner', 'MAJ Éléments à Étalonner'), ('maj_mouvement_materiel', 'Mouvement Matériel'), ('planning_etalonnage', 'Planning Étalonnage'), ('planning_maintenance', 'Planning Maintenance'), ('moyens_mesure', 'Capabilité des Moyens'), ('balances', 'Capabilité des Balances'), ('exploitation_metrologique', 'Exploitation Métrologique'), ('verification_etuves', 'Vérification Étuves'), ('donnees_balances', 'Données Balances'), ('masses_etalons', 'Données Masses Étalons'), ('donnees_materiel', 'Données Matériel'), ('periodicite', 'Périodicité'), ('instruction_etalonnage', 'Instruction Étalonnage'), ('type_intervention', 'Type Intervention'), ('accreditation', 'Accréditation'), ('conges', 'Congés'), ('attestations', 'Attestations'), ('demandes_achat', "Demandes d'Achat"), ('specimen_signature', 'Spécimen Signature'), ('archive_ged', 'Archive GED'), ('services_familles_ged', 'Services/Familles GED'), ('droits_ged', 'Droits GED'), ('suivi_modifications', 'Suivi Modifications'), ('gestion_droits_acces', "Gestion Droits d'Accès"), ('donnees_informatique', 'Données Informatique'), ('parametrage_general', 'Paramétrage Général')], max_length=60, verbose_name='module'),
        ),
    ]
